export interface Candidate {
  id: string;
  name: string;
  party: string;
  image?: string; // Path to candidate image
}

export interface Position {
  id: string;
  title: string;
  description: string;
  maxSelections: number;
  candidates: Candidate[];
}

// Mock data for election positions and candidates
// In a real application, this would come from an API
export const positions: Position[] = [
  {
    id: "house-rep-zamboanga-first",
    title: "Member, House of Representatives - Zamboanga Del Sur (First District)",
    description: "Representatives of Zamboanga Del Sur's First Legislative District in the House of Representatives.",
    maxSelections: 1,
    candidates: [
      { id: "zambo1-hr1", name: "ABDUHALIM, AL", party: "IND" },
      { id: "zambo1-hr2", name: "CHUA, KAT SIKAT", party: "IND" },
      { id: "zambo1-hr3", name: "OLASO, KAISER ADAN", party: "NP" },
      { id: "zambo1-hr4", name: "PAREJA, PINPIN", party: "LAKAS" },
    ]
  },
  {
    id: "house-rep-zamboanga-second",
    title: "Member, House of Representatives - Zamboanga Del Sur (Second District)",
    description: "Representatives of Zamboanga Del Sur's Second Legislative District in the House of Representatives.",
    maxSelections: 1,
    candidates: [
      { id: "zambo2-hr1", name: "DALIPE, JOHN", party: "LAKAS" },
      { id: "zambo2-hr2", name: "ISMAEL, ANDER", party: "IND" },
      { id: "zambo2-hr3", name: "NATIVIDAD, MICHELLE DANIEL", party: "PDPLBN" },
      { id: "zambo2-hr4", name: "PEREZ, KAP JERRY TOTONG", party: "AZAP" },
      { id: "zambo2-hr5", name: "SALI, DARLENE", party: "IND" },
    ]
  },
  {
    id: "mayor-zamboanga",
    title: "Mayor - City of Zamboanga",
    description: "The chief executive of the City of Zamboanga.",
    maxSelections: 1,
    candidates: [
      { id: "zambo-m1", name: "ANNI, LAYLA", party: "IND" },
      { id: "zambo-m2", name: "DALIPE, MANNIX", party: "LAKAS" },
      { id: "zambo-m3", name: "IBBAH, DENNIER", party: "IND" },
      { id: "zambo-m4", name: "NATIVIDAD, SIR PETE", party: "IND" },
      { id: "zambo-m5", name: "NEGRETE, ORLANDO", party: "IND" },
      { id: "zambo-m6", name: "OLASO, KHYMER ADAN", party: "NP" },
    ]
  },
  {
    id: "vice-mayor-zamboanga",
    title: "Vice-Mayor - City of Zamboanga",
    description: "The second-highest executive official in the City of Zamboanga.",
    maxSelections: 1,
    candidates: [
      { id: "zambo-vm1", name: "CLIMACO, BENG", party: "AZAP" },
      { id: "zambo-vm2", name: "GUINGONA, VINO", party: "LAKAS" },
      { id: "zambo-vm3", name: "TAUP, SOPHIA", party: "IND" },
    ]
  },
  {
    id: "councilor-zamboanga-first",
    title: "Councilor - City of Zamboanga (First District)",
    description: "Members of the city council for Zamboanga City's First District.",
    maxSelections: 8,
    candidates: [
      { id: "zambo1-c1", name: "ASDALI, BEN DIGONG", party: "PFP" },
      { id: "zambo1-c2", name: "ATILANO, BONG", party: "LAKAS" },
      { id: "zambo1-c3", name: "CABATO, BODAY", party: "LAKAS" },
      { id: "zambo1-c4", name: "CINCO, MIKE", party: "NP" },
      { id: "zambo1-c5", name: "DELOS SANTOS, IDOL RUIZ", party: "IND" },
      { id: "zambo1-c6", name: "DIONES, BENJIE", party: "IND" },
      { id: "zambo1-c7", name: "ENRIQUEZ, ATTY. GIAN", party: "AZAP" },
      { id: "zambo1-c8", name: "ESTEBAN, JOEL", party: "AZAP" },
      { id: "zambo1-c9", name: "HOSSEINI, KUYA MATTHEW", party: "IND" },
      { id: "zambo1-c10", name: "JIMENEZ, JAWO", party: "LAKAS" },
      { id: "zambo1-c11", name: "JIMENEZ, VLADIMIR", party: "NP" },
      { id: "zambo1-c12", name: "JULIAN, JACKIE", party: "AZAP" },
      { id: "zambo1-c13", name: "MACROHON, LIT-LIT", party: "IND" },
      { id: "zambo1-c14", name: "MARIANO, CHARLIE", party: "LAKAS" },
      { id: "zambo1-c15", name: "OLVINAR, KUYA POLOY", party: "LAKAS" },
      { id: "zambo1-c16", name: "OMAGA, KING", party: "LAKAS" },
      { id: "zambo1-c17", name: "SADAIN, ATTY. MEL", party: "NP" },
      { id: "zambo1-c18", name: "SANTOS, JOEY PAPAYA", party: "LAKAS" },
      { id: "zambo1-c19", name: "VALESCO, GERKY", party: "LAKAS" },
      { id: "zambo1-c20", name: "VICENTE, DAN", party: "AZAP" },
    ]
  },
  {
    id: "councilor-zamboanga-second",
    title: "Councilor - City of Zamboanga (Second District)",
    description: "Members of the city council for Zamboanga City's Second District.",
    maxSelections: 8,
    candidates: [
      { id: "zambo2-c25", name: "SIASON, JAMES", party: "LAKAS" },
      { id: "zambo2-c26", name: "SIMBAJON, BONG", party: "AZAP" },
      { id: "zambo2-c27", name: "TORIBIO, JESSE", party: "KTPNAN" },
      { id: "zambo2-c28", name: "TURABIN, IBS", party: "IND" },
      { id: "zambo2-c29", name: "VILLAFLORES, KIM", party: "LAKAS" },
    ]
  },
  {
    id: "senators",
    title: "Senator",
    description: "Members of the Senate, the upper chamber of Congress.",
    maxSelections: 12,
    candidates: [
      { id: "s1", name: "ABALOS, BENHUR", party: "PFP" },
      { id: "s2", name: "ACERON, JOVILYN", party: "IND" },
      { id: "s3", name: "ACLAN, KUYA", party: "IND" },
      { id: "s4", name: "ACOPIADO, MERCEDITA", party: "IND" },
      { id: "s5", name: "ADONIS, JEROME", party: "MKBYN" },
      { id: "s6", name: "ADORABLE, ABEL", party: "IND" },
      { id: "s7", name: "ADVINCULA, DINGBICOL", party: "IND" },
      { id: "s8", name: "ADVINCULA, PETER JOEMEL", party: "IND" },
      { id: "s9", name: "AGAD, ROBERT", party: "IND" },
      { id: "s10", name: "AGUILAR, CEZ", party: "WPP" },
      { id: "s11", name: "ALCANTARA, ERIC", party: "IND" },
      { id: "s12", name: "AMAD, WILSON", party: "IND" },
      { id: "s13", name: "AMIR HUSSIN, SALIPADA", party: "PM" },
      { id: "s14", name: "ANCAJAS, NELSON", party: "IND" },
      { id: "s15", name: "ANDAMO, NARS ALYN", party: "MKBYN" },
      { id: "s16", name: "ANDRADA, KUYA MANNY", party: "IND" },
      { id: "s17", name: "ANDRINO, BOBIE", party: "IND" },
      { id: "s18", name: "APOLINARIO, JOEL", party: "PM" },
      { id: "s19", name: "AQUINO, BAM", party: "KNP" },
      { id: "s20", name: "AQUINO, PRIMO", party: "IND" },
      { id: "s21", name: "ARAMBULO, RONNEL", party: "MKBYN" },
      { id: "s22", name: "ARCEGA, GERALD", party: "PM" },
      { id: "s23", name: "ARELLANO, ERNESTO", party: "KTPNAN" },
      { id: "s24", name: "ARES, JERSON", party: "IND" },
      { id: "s25", name: "ARGUELLES, RICARDA", party: "IND" },
      { id: "s26", name: "ARTAJO, ADAM", party: "IND" },
      { id: "s27", name: "BAJO, ISMAEL", party: "IND" },
      { id: "s28", name: "BALITE, KAKA", party: "IND" },
      { id: "s29", name: "BALLON, ROBERTO", party: "IND" },
      { id: "s30", name: "BALMAS, JAIME", party: "KBL" },
      { id: "s31", name: "BANOSAN, LORETO", party: "IND" },
      { id: "s32", name: "BASILAN, RODOLFO", party: "IND" },
      { id: "s33", name: "BAUTISTA, EDUARDO", party: "IND" },
      { id: "s34", name: "BENIGA, ELVIS", party: "IND" },
      { id: "s35", name: "BIAZON, DAVE", party: "IND" },
      { id: "s36", name: "BILLONES, MARIA CHARITO", party: "IND" },
      { id: "s37", name: "BINAY, ABBY", party: "NPC" },
      { id: "s38", name: "BONAYOG, CHITO", party: "IND" },
      { id: "s39", name: "BONDOC, JIMMY", party: "PDPLBN" },
      { id: "s40", name: "BONG REVILLA,RAMON, JR.", party: "LAKAS" },
      { id: "s41", name: "BOSITA, BONIFACIO", party: "IND" },
      { id: "s42", name: "BOVIER, WARLY", party: "IND" },
      { id: "s43", name: "BROSAS, ARLENE", party: "MKBYN" },
      { id: "s44", name: "BRUCE, HERNANDO", party: "IND" },
      { id: "s45", name: "BUNAYOG, INJIM", party: "IND" },
      { id: "s46", name: "BUNILLA, JOSE", party: "IND" },
      { id: "s47", name: "CABALIDA, JUNE KING SBC", party: "IND" },
      { id: "s48", name: "CABONEGRO, ROY", party: "DPP" },
      { id: "s49", name: "CADION, LEO", party: "IND" },
      { id: "s50", name: "CAPUNO, ONDONG", party: "IND" },
      { id: "s51", name: "CAPUYAN, ALLEN", party: "PPP" },
      { id: "s52", name: "CASIMRA, KHALED", party: "IND" },
      { id: "s53", name: "CASIÑO, TEDDY", party: "MKBYN" },
      { id: "s54", name: "CASIPONG, AGAPITO", party: "IND" },
      { id: "s55", name: "CASTRO, TEACHER FRANCE", party: "MKBYN" },
      { id: "s56", name: "CATURAN, MIG", party: "IND" },
      { id: "s57", name: "CAUSING, BERTENI", party: "BUNYOG" },
      { id: "s58", name: "CAY, LAUREL", party: "KKK" },
      { id: "s59", name: "CAYETANO, PIA", party: "NP" },
      { id: "s60", name: "CHACLAG, GABRIEL", party: "IND" },
      { id: "s61", name: "CHAN, DAVID PAUL", party: "IND" },
      { id: "s62", name: "CHAN, EMILIO", party: "IND" },
      { id: "s63", name: "CHICO, RAFFY", party: "PM" },
      { id: "s64", name: "CUATCHIN, SHIRLY", party: "WPP" },
      { id: "s65", name: "D'ANGELO, DAVID", party: "BUNYOG" },
      { id: "s66", name: "DE ALBAN,ATTORNEY ANGELO", party: "IND" },
      { id: "s67", name: "DE GUZMAN, KA LEODY", party: "PLM" },
      { id: "s68", name: "DE GUZMAN, ORLANDO", party: "IND" },
      { id: "s69", name: "DELA ROSA, BATO", party: "PDPLBN" },
      { id: "s70", name: "DELGADO, JOSEPH", party: "IND" },
      { id: "s71", name: "DELOS REYES, PHIL", party: "IND" },
      { id: "s72", name: "DIAZ, DING", party: "PPP" },
      { id: "s73", name: "DITANONGUN, SUNANG", party: "IND" },
      { id: "s74", name: "DOMAGTOY, GEM", party: "IND" },
      { id: "s75", name: "DOMINGO, KA SONNY", party: "IND" },
      { id: "s76", name: "DORINGO, NANAY MIMI", party: "MKBYN" },
      { id: "s77", name: "DUQUE, EDGARDO", party: "IND" },
      { id: "s78", name: "DY, JOSEPH", party: "IND" },
      { id: "s79", name: "ENCARNACION, ALEXANDER", party: "IND" },
      { id: "s80", name: "ERA, MARIA FE", party: "IND" },
      { id: "s81", name: "ESCOBAL, ARNEL", party: "PM" },
      { id: "s82", name: "ESCOBAR, JOHN", party: "IND" },
      { id: "s83", name: "ESPIRITU, LUKE", party: "PLM" },
      { id: "s84", name: "ESTRELLA, IDOLODI", party: "IND" },
      { id: "s85", name: "FLORANDA, MODY PISTON", party: "MKBYN" },
      { id: "s86", name: "GAMBOA, MARC LOUIE", party: "IND" },
      { id: "s87", name: "GARGARITA, JONRY", party: "IND" },
      { id: "s88", name: "GO, BONG GO", party: "PDPLBN" },
      { id: "s89", name: "GONZALES, NORBERTO", party: "PDSP" },
      { id: "s90", name: "GUIGAYUMA, JB", party: "KKK" },
      { id: "s91", name: "HINLO, JAYVEE", party: "PDPLBN" },
      { id: "s92", name: "HONASAN, GRINGO", party: "RP" },
      { id: "s93", name: "INTE, VICTOR", party: "IND" },
      { id: "s94", name: "JOSE, RELLY JR.", party: "KBL" },
      { id: "s95", name: "JUMALON, ALICE", party: "IND" },
      { id: "s96", name: "KOKKINARAS, BAE DALAN", party: "WPP" },
      { id: "s97", name: "LACSON, PING", party: "IND" },
      { id: "s98", name: "LAGARE, SIXTO", party: "IND" },
      { id: "s99", name: "LAGUE, ALEX", party: "IND" },
      { id: "s100", name: "LAMBINO, RAUL", party: "PDPLBN" },
      { id: "s101", name: "LAMOSTE, PRINCEDATU", party: "WPP" },
      { id: "s102", name: "LAPID, LITO", party: "NPC" },
      { id: "s103", name: "LEE, MANOY WILBERT", party: "AKSYON" },
      { id: "s104", name: "LIDASAN, AMIRAH", party: "MKBYN" },
      { id: "s105", name: "LOPEZ, BETH", party: "IND" },
      { id: "s106", name: "LUBARBIO, HAPPY", party: "IND" },
      { id: "s107", name: "LUCAÑAS, MELCHOR", party: "IND" },
      { id: "s108", name: "MACARAEG, ROMEO", party: "WPP" },
      { id: "s109", name: "MAGTIRA, DANIEL", party: "IND" },
      { id: "s110", name: "MAIQUEZ, FREDIE", party: "IND" },
      { id: "s111", name: "MALINAO, GETTER", party: "IND" },
      { id: "s112", name: "MANALO, MAGNO", party: "IND" },
      { id: "s113", name: "MAQUISO, ARTEMIO", party: "IND" },
      { id: "s114", name: "MARCOLETA, RODANTE", party: "IND" },
      { id: "s115", name: "MARCOS, FRANCIS LEO", party: "IND" },
      { id: "s116", name: "MARCOS, IMEE R.", party: "NP" },
      { id: "s117", name: "MARCOS TALLANO TAGEAN", party: "IND" },
      { id: "s118", name: "MARQUEZ, NORMAN", party: "IND" },
      { id: "s119", name: "MARTINEZ, ERIC", party: "IND" },
      { id: "s120", name: "MATA, DOC MARITES", party: "IND" },
      { id: "s121", name: "MATULA, ATTY. SONNY", party: "WPP" },
      { id: "s122", name: "MAZA, LIZA", party: "MKBYN" },
      { id: "s123", name: "MENDOZA, HEIDI", party: "IND" },
      { id: "s124", name: "MENDOZA, KA MARTIN", party: "IND" },
      { id: "s125", name: "MENIANO, LUTHER", party: "IND" },
      { id: "s126", name: "MONTEALTO, LIGTAS", party: "IND" },
      { id: "s127", name: "MONTEMAYOR, JOEY", party: "IND" },
      { id: "s128", name: "MUSTAPHA, SUBAIR", party: "WPP" },
      { id: "s129", name: "NEGAPATAN, ERIC", party: "IND" },
      { id: "s130", name: "NICOLAS, RICHARD", party: "KBL" },
      { id: "s131", name: "NOEL, REX", party: "IND" },
      { id: "s132", name: "OLIVAR, JOSE JESSIE", party: "IND" },
      { id: "s133", name: "OLONAN, HENRY", party: "WPP" },
      { id: "s134", name: "ONG, DOC WILLIE", party: "AKSYON" },
      { id: "s135", name: "ONGJOCO, OSCAR", party: "IND" },
      { id: "s136", name: "ORDIALES, PETE", party: "WPP" },
      { id: "s137", name: "PACQUIAO, MANNY PACMAN", party: "PFP" },
      { id: "s138", name: "PACQUIAO, ROEL", party: "IND" },
      { id: "s139", name: "PADILLA, JANICE", party: "IND" },
      { id: "s140", name: "PAGARAGAN, SUPER MAR", party: "PM" },
      { id: "s141", name: "PALIZA, NHELING", party: "IND" },
      { id: "s142", name: "PALOMARES, DIEGO JR.", party: "PM" },
      { id: "s143", name: "PANGILINAN, KIKO", party: "LP" },
      { id: "s144", name: "PAR, TONY", party: "IND" },
      { id: "s145", name: "PARTOSA, EULOGIO JR.", party: "IND" },
      { id: "s146", name: "PEREZ, EPIFANIO", party: "IND" },
      { id: "s147", name: "PIMENTEL, BONG BONG", party: "WPP" },
      { id: "s148", name: "PLAZA, RASTAMAN", party: "IND" },
      { id: "s149", name: "QUERUBIN, ARIEL PORFIRIO", party: "NP" },
      { id: "s150", name: "QUIBOLOY, APOLLO", party: "IND" },
      { id: "s151", name: "RAMOS, PRINCESS JADE", party: "IND" },
      { id: "s152", name: "RAMOS, DANILO", party: "MKBYN" },
      { id: "s153", name: "RED, KUYA WILY", party: "IND" },
      { id: "s154", name: "RED, RANDY", party: "IND" },
      { id: "s155", name: "RESTUM, RANDY", party: "IND" },
      { id: "s156", name: "REVILLAME, WILLIE WIL", party: "IND" },
      { id: "s157", name: "REYES, JAMES", party: "IND" },
      { id: "s158", name: "RICABLANCA, WILLIE", party: "IND" },
      { id: "s159", name: "RODRIGUEZ, ATTY. VIC", party: "IND" },
      { id: "s160", name: "ROSALES, ELPIDIO JR.", party: "KBL" },
      { id: "s161", name: "RUBI, EDMON", party: "IND" },
      { id: "s162", name: "SABIT, VIRGINIA", party: "IND" },
      { id: "s163", name: "SAHIDULLA, NUR-ANA", party: "IND" },
      { id: "s164", name: "SALAPANTAN, JIMMY", party: "IND" },
      { id: "s165", name: "SALIH, NAJAR", party: "PM" },
      { id: "s166", name: "SALVADOR, PHILLIP IPE", party: "PDPLBN" },
      { id: "s167", name: "SAN RAMON, MULO", party: "IND" },
      { id: "s168", name: "SANCHEZ, MELISSA", party: "IND" }
    ]
  },
  {
    id: "house-rep",
    title: "Member, House of Representatives",
    description: "Representatives of legislative districts in the House of Representatives.",
    maxSelections: 1,
    candidates: [
      { id: "hr1", name: "Alama, Johram", party: "IND" },
      { id: "hr2", name: "Malapitan, Oca", party: "NP" },
      { id: "hr3", name: "Malonzo, Rey", party: "KNP" },
    ]
  },
  {
    id: "mayor",
    title: "Mayor",
    description: "The chief executive of a city or municipality.",
    maxSelections: 1,
    candidates: [
      { id: "m1", name: "Cañete, Richard", party: "IND" },
      { id: "m2", name: "Malapitan, Along", party: "NP" },
      { id: "m3", name: "Malunes, Ronnie", party: "IND" },
      { id: "m4", name: "Trillanes, Antonio IV", party: "AKSYON" },
      { id: "m5", name: "Villanueva, Danny", party: "IND" },
    ]
  },
  {
    id: "vice-mayor",
    title: "Vice-Mayor",
    description: "The second-highest executive official in a city or municipality.",
    maxSelections: 1,
    candidates: [
      { id: "vm1", name: "Lustre, Dante", party: "IND" },
      { id: "vm2", name: "Malonzo, PJ", party: "AKSYON" },
      { id: "vm3", name: "Teh, Karina", party: "NP" },
      { id: "vm4", name: "Timbol, Joseph", party: "IND" },
      { id: "vm5", name: "Tobias, Rolando", party: "IND" },
    ]
  },
  {
    id: "sanggunian",
    title: "Member, Sangguniang Panlungsod",
    description: "Members of the city or municipal council.",
    maxSelections: 6,
    candidates: [
      { id: "sp1", name: "Adalem, Topet", party: "NP" },
      { id: "sp2", name: "Bacolod, Leah", party: "NP" },
      { id: "sp3", name: "Barretto, Marjorie", party: "NP" },
      { id: "sp4", name: "Bunag, Mickey", party: "AKSYON" },
      { id: "sp5", name: "Caralde, Alex", party: "NP" },
      { id: "sp6", name: "De Leon, Tyrone Sr.", party: "IND" },
      { id: "sp7", name: "Domasgk, Roman Jr.", party: "IND" },
      { id: "sp8", name: "Faustino, Mining", party: "AKSYON" },
      { id: "sp9", name: "Hernandez, Vince", party: "NP" },
      { id: "sp10", name: "Leonardo, Angie", party: "AKSYON" },
      { id: "sp11", name: "Lipata, Buddy", party: "IND" },
      { id: "sp12", name: "Malupitan, Enteng", party: "NP" },
    ]
  },
  {
    id: "party-list",
    title: "Party List",
    description: "Representatives of marginalized and underrepresented sectors.",
    maxSelections: 1,
    candidates: [
      { id: "pl1", name: "4PS", party: "PAGTIBAYIN AT PALAGUIN ANG PANGKABUHAYANG PILIPINO" },
      { id: "pl2", name: "PPP", party: "PUWERSA NG PILIPINONG PANDAGAT" },
      { id: "pl3", name: "FPJ PANDAY BAYANIHAN", party: "FPJ PANDAY BAYANIHAN PARTYLIST" },
      { id: "pl4", name: "KABATAAN", party: "KABATAAN PARTYLIST" },
      { id: "pl5", name: "DUTERTE YOUTH", party: "DUTY TO ENERGIZE THE REPUBLIC THROUGH THE ENLIGHTENMENT OF THE YOUTH" },
      { id: "pl6", name: "ML", party: "MAMAMAYANG LIBERAL" },
      { id: "pl7", name: "PBBM", party: "PILIPINAS BABANGON MULI" },
      { id: "pl8", name: "P3PWD", party: "KOMUNIDAD NG PAMILYA PASYENTE AT PERSONS WITH DISABILITIES" },
      { id: "pl9", name: "MURANG KURYENTE", party: "MURANG KURYENTE PARTYLIST" },
      { id: "pl10", name: "BICOL SARO", party: "BICOL SARO" },
      { id: "pl11", name: "IPATUPAD", party: "IPATUPAD FOR WORKERS, INC." },
      { id: "pl12", name: "PATROL", party: "PUBLIC SAFETY ALLIANCE FOR TRANSFORMATION AND RULE OF LAW, INC." },
      { id: "pl13", name: "JUAN PINOY", party: "JUAN-PINAGKAISANG ORDINARYONG MAMAMAYAN PARA YUMABONG" },
      { id: "pl14", name: "ARTE", party: "ADVOCATES FOR RETAIL, FASHION, TEXTILE, TRADITION, EVENTS & AND CREATIVE SERVICES SECTOR" },
      { id: "pl15", name: "WIFI", party: "WALANG IWANAN SA FREE INTERNET, INC." },
      { id: "pl16", name: "MAAGAP", party: "MOVEMENT OF ACTIVE APOSTOLIC GUARDIANS ASSOCIATION OF THE PHILIPPINES" },
      { id: "pl17", name: "UNITED SENIOR CITIZENS", party: "UNITED SENIOR CITIZENS KOALITION NG PILIPINAS" },
      { id: "pl18", name: "EPANAW SAMBAYANAN", party: "MINDANAO INDIGENOUS PEOPLES CONFERENCE FOR PEACE AND DEVELOPMENT" },
      { id: "pl19", name: "AKO PADAYON", party: "AKO PADAYON PILIPINO PARTYLIST" },
      { id: "pl20", name: "TUCP", party: "TRADE UNION CONGRESS PARTY" },
      { id: "pl21", name: "ACT TEACHERS", party: "ACT TEACHERS PARTY-LIST" },
      { id: "pl22", name: "1PACMAN", party: "ONE PATRIOTIC COALITION OF MARGINALIZED NATIONALS INC." },
      { id: "pl23", name: "TGP", party: "TALINO AT GALING NG PINOY" },
      { id: "pl24", name: "DUMPER PTDA", party: "DUMPER PHILIPPINES TAXI DRIVERS ASSOCIATION, INC." },
      { id: "pl25", name: "ANAKALUSUGAN", party: "ALAGAAN NATIN ATING KALUSUGAN INC." },
      { id: "pl26", name: "AKSYON DAPAT", party: "AKSYON DAPAT INCORPORATED" },
      { id: "pl27", name: "BHW", party: "BARANGAY HEALTH WELLNESS" },
      { id: "pl28", name: "SULONG DIGNIDAD", party: "SULONG DIGNIDAD REGIONAL POLITICAL PARTY" },
      { id: "pl29", name: "BATANG QUIAPO", party: "SULONG MGA BATANG QUIAPO" },
      { id: "pl30", name: "PBA", party: "PWERSA NG BAYANING ATLETA" },
      { id: "pl31", name: "GILAS", party: "GENERASYONG INIAALAY LAGI ANG SARILI" },
      { id: "pl32", name: "AKO ILOCANO AKO", party: "AKO ILOCANO AKO" },
      { id: "pl33", name: "PAMILYANG MAGSASAKA", party: "PAMILYANG MAGSASAKA" },
      { id: "pl34", name: "CLICK PARTY", party: "COMPUTER LITERACY INNOVATION CONNECTIVITY AND KNOWLEDGE" },
      { id: "pl35", name: "ABANTE BISDAK", party: "ABANTE BISDAK" },
      { id: "pl36", name: "MANILA TEACHERS", party: "MANILA TEACHERS' SAVINGS AND LOAN ASSOCIATION, INC." },
      { id: "pl37", name: "PAMANA", party: "IBALIK ANG KULTURANG PAMANA MOVEMENT" },
      { id: "pl38", name: "NANAY", party: "NANAY" },
      { id: "pl39", name: "KM NGAYON NA", party: "KILOS MAMAMAYAN NGAYON NA" },
      { id: "pl40", name: "BABAE AKO", party: "BABAE AKO PARA SA BAYAN INC." },
      { id: "pl41", name: "ARISE", party: "ALLIANCE FOR RESILIENCE SUSTAINABILITY AND EMPOWERMENT" },
      { id: "pl42", name: "MAGDALO", party: "MAGDALO PARA SA PILIPINO" },
      { id: "pl43", name: "APEC", party: "ASSOCIATION OF PHILIPPINE ELECTRIC COOPERATIVES" },
      { id: "pl44", name: "MAGBUBUKID", party: "MAMAMAYAN PARA SA GOBYERNONG BUBUKLOD SA MGA ISIP AT DIWA NG MGA PILIPINO" },
      { id: "pl45", name: "SSS-GSIS PENSYONADO", party: "SSS-GSIS PENSYONADO" },
      { id: "pl46", name: "GABRIELA", party: "GABRIELA WOMEN'S PARTY" },
      { id: "pl47", name: "TINGOG", party: "TINGOG SINIRANGAN" },
      { id: "pl48", name: "APAT-DAPAT", party: "ANG PROGRAMANG AASENSO TAUMBAYAN - DREAM, ACT, PARTICIPATE, ADVOCATE FOR SUSTAINABLE TRANSFORMATION" },
      { id: "pl49", name: "AHON MAHIRAP", party: "AHON MAHIRAP" },
      { id: "pl50", name: "UGB", party: "UNYON NG MGA GABAY NG BAYAN" },
      { id: "pl51", name: "AKBAYAN", party: "AKBAYAN CITIZENS' ACTION PARTY" },
      { id: "pl52", name: "AGIMAT", party: "AGIMAT NG MASA" },
      { id: "pl53", name: "PHILRECA", party: "PHILIPPINE RURAL ELECTRIC COOPERATIVES ASSOCIATION, INC." },
      { id: "pl54", name: "KAPUSO PM", party: "KABALIKAT PATUNGO SA UMUUNLAD NA SISTEMATIKO AT ORGANISADONG PANGKABUHAYAN" },
      { id: "pl55", name: "ILOCANO DEFENDERS", party: "ILOCANO DEFENDERS INC." },
      { id: "pl56", name: "1-RIDER PARTY-LIST", party: "ANG BUKLOD NG MGA MOTORISTA NG PILIPINAS" },
      { id: "pl57", name: "TICTOK", party: "TULONG IPAMAHAGI SA COMMUNIDAD TUNGO ONSA KAUNLARAN" },
      { id: "pl58", name: "WAGE HIKE", party: "PARTIDO TRABAHO AT WAGE HIKE" },
      { id: "pl59", name: "BAYAN MUNA", party: "BAYAN MUNA" },
      { id: "pl60", name: "ANG PROBINSIYANO", party: "ALYANSA NG MGA MAMAMAYANG PROBINSIYANO" },
      { id: "pl61", name: "BANAT", party: "BANAT BARANGAY NATIN" },
      { id: "pl62", name: "SBP", party: "SERBISYO SA BAYAN PARTY" },
      { id: "pl63", name: "BUHAY", party: "BUHAY HAYAAN YUMABONG" },
      { id: "pl64", name: "TULUNGAN TAYO", party: "TULUNGAN TAYO" },
      { id: "pl65", name: "SAGIP", party: "SOCIAL AMELIORATION & GENUINE INTERVENTION ON POVERTY" },
      { id: "pl66", name: "BTS", party: "BAYANING TSUPER BAYANING TSUPER" },
      { id: "pl67", name: "VENDORS", party: "VENDOR SAMAHAN NG MGA MANININDANG PILIPINO" },
      { id: "pl68", name: "ACT-CIS", party: "ANTI-CRIME AND TERRORISM - COMMUNITY INVOLVEMENT AND SUPPORT, INC." },
      { id: "pl69", name: "AKTIBONG KAAGAPAY", party: "AKTIBONG KAAGAPAY NG MGA MANGGAGAWA" },
      { id: "pl70", name: "ASENSO PINOY", party: "ASENSO PINOY" },
      { id: "pl71", name: "SOLO PARENTS", party: "SOLO PARENTS" },
      { id: "pl72", name: "ANG KOMADRONA", party: "ANG KOMADRONA INC." },
      { id: "pl73", name: "PROMDI", party: "ABAG PROMDI" },
      { id: "pl74", name: "PUSONG PINOY", party: "PUSONG PINOY" },
      { id: "pl75", name: "KUSUG TAUSUG", party: "KUSUG TAUSUG" },
      { id: "pl76", name: "DAMAYANG FILIPINO", party: "DAMAYANG FILIPINO MOVEMENT, INCORPORATED" },
      { id: "pl77", name: "MPBL", party: "MAHARLIKANG PILIPINO SA BAGONG LIPUNAN" },
      { id: "pl78", name: "ANGAT AKMA AT TAMA", party: "ANG ATMA AT TAMA" },
      { id: "pl79", name: "KALINGA", party: "ADVOCACY FOR SOCIAL EMPOWERMENT AND NATION" },
      { id: "pl80", name: "BOSES PARTY-LIST", party: "BOSES PARTY-LIST" },
      { id: "pl81", name: "ARANGKADA PILIPINO", party: "ARANGKADA PILIPINO" },
      { id: "pl82", name: "AANGAT TAYO", party: "AANGAT TAYO PARTYLIST" },
      { id: "pl83", name: "OFW", party: "ONE FILIPINOS WORLDWIDE PARTYLIST" },
      { id: "pl84", name: "BIDA KATAGUMPAY", party: "BAYAN ITAYO ANG DANGAL NG AGRIKULTURA KASAMA SA TAGUMPAY" },
      { id: "pl85", name: "KAMANGGAGAWA", party: "KAMPIHAN NG MGA MARALITA AT MANGGAGAWA" },
      { id: "pl86", name: "BFF", party: "BALIKATAN OF FILIPINO FAMILIES" },
      { id: "pl87", name: "BUNYOG", party: "BUNYOG (PAGKAKAISA)" },
      { id: "pl88", name: "AGRI", party: "AGRI-AGRA NA REPORMA PARA SA MAGSASAKA NG PILIPINAS" },
      { id: "pl89", name: "SENIOR CITIZENS", party: "COALITION OF ASSOCIATIONS OF SENIOR CITIZENS IN THE PHILIPPINES" },
      { id: "pl90", name: "4K", party: "KABABAIHAN KABALIKATAN PARA SA KAPAKANAN AT KAUNLARAN NG BAYAN" },
      { id: "pl91", name: "PBP", party: "PARTIDO SA BAG-ONG PILIPINO" },
      { id: "pl92", name: "ONE COOP", party: "AURORA INTEGRATED MULTI-PURPOSE COOPERATIVE (AIMCOOP)" },
      { id: "pl93", name: "CIBAC", party: "CITIZENS' BATTLE AGAINST CORRUPTION" },
      { id: "pl94", name: "BH - BAGONG HENERASYON", party: "BAGONG HENERASYON" },
      { id: "pl95", name: "1AGILA", party: "1 AGILA-ALALAYANG AGILA PARA SA BAYAN, INC." },
      { id: "pl96", name: "EDUAKSYON", party: "EDUAKSYON" },
      { id: "pl97", name: "ANG TINIG NG SENIORS", party: "ANG TINIG NG SENIOR CITIZENS SA FILIPINAS, INC." },
      { id: "pl98", name: "BG PARTY-LIST", party: "BISAYA GYUD PARTY-LIST" },
      { id: "pl99", name: "PINOY AKO", party: "PINOY AKO" },
      { id: "pl100", name: "H.E.L.P. PILIPINAS", party: "HEALTH, EDUCATION, LIVELIHOOD PROGRAM OF THE PHILIPPINES" },
      { id: "pl101", name: "HEALTH WORKERS", party: "HEALTH WORKERS PARTY-LIST" },
      { id: "pl102", name: "PEOPLE'S CHAMP", party: "PEOPLES CHAMP GUARDIANS PARTYLIST" },
      { id: "pl103", name: "AA-KASOSYO PARTY", party: "KASOSYO PRODUCER-CONSUMER EXCHANGE ASSOCIATION, INC." },
      { id: "pl104", name: "SOLID NORTH PARTY", party: "SOLIDARITY OF NORTHERN LUZON PEOPLE'S PARTY" },
      { id: "pl105", name: "ABAMIN", party: "ABANTE MINDANAO, INC." },
      { id: "pl106", name: "TRABAHO", party: "TAGAPAGTAGUYOD NG MGA REPORMA AT ADHIKAING BABALIKAT AT HAHANGO SA MGA OPORTUNIDAD PARA SA MGA PILIPINO" },
      { id: "pl107", name: "ANGKASANGGA", party: "ANG KASANGGA NG MANGUNGUMA - OWA MANGUNGUMA" },
      { id: "pl108", name: "TODA", party: "AKSYON TOWARDS DEVELOPMENT AND ACTION" },
      { id: "pl109", name: "TURISMO", party: "TURISMO ISULONG MO" },
      { id: "pl110", name: "ABONO", party: "ABONO PARTYLIST" },
      { id: "pl111", name: "ASAP NA", party: "ALYANSA LABAN SA SUBSTANCE ABUSE PARA SA BAGONG PILIPINAS NATIN" },
      { id: "pl112", name: "LINGAP", party: "LIGA NG NAGKAKAISANG MAHIHIRAP" },
      { id: "pl113", name: "UNITED FRONTLINERS", party: "UNITED FRONTLINERS OF THE PHILIPPINES" },
      { id: "pl114", name: "KASAMBAHAY", party: "KASAMBAHAY TAYO, INC." },
      { id: "pl115", name: "TUTOK TO WIN", party: "TUTOK TO WIN" },
      { id: "pl116", name: "AKO OFW", party: "ADVOCATES & KEEPERS ORGANISASYON & LABAN" },
      { id: "pl117", name: "AGAP", party: "AGRICULTURAL SECTOR ALLIANCE OF THE PHILIPPINES" },
      { id: "pl118", name: "1TAHANAN", party: "1TAHANAN INC." },
      { id: "pl119", name: "COOP-NATCCO", party: "COOPERATIVE NATCCO NETWORK PARTY" },
      { id: "pl120", name: "KABAYAN", party: "KABALIKAT NG MAMAMAYAN" },
      { id: "pl121", name: "1MUNTI", party: "1MUNTI" },
      { id: "pl122", name: "PINOY WORKERS", party: "PEOPLE WORKING FOR THE DEVELOPMENT OF THE PHILIPPINES" },
      { id: "pl123", name: "API PARTY", party: "ABANTE PANGASINAN - ILOKANO PARTY" },
      { id: "pl124", name: "AKO BISAYA", party: "AKO BISAYA INC." },
      { id: "pl125", name: "KAMALAYAN", party: "KALIPUNAN NG MARALITA AT MALAYANG MAMAMAYA, INC." },
      { id: "pl126", name: "AKO TANOD", party: "AKO TANOD INCORPORATED" },
      { id: "pl127", name: "PROBINSYANO AKO", party: "PROBINSYANO AKO" },
      { id: "pl128", name: "KABABAIHAN", party: "HANAY NG MGA KABABAIHAN AT KANILANG MGA KASANGGA SA LIPUNAN" },
      { id: "pl129", name: "RAM", party: "REBOLUSONARYONG ALYANSANG MAKABANSA" },
      { id: "pl130", name: "ALONA", party: "ALLIANCE OF ORGANIZATIONS, NETWORKS, AND ASSOCIATIONS OF THE PHILIPPINES" },
      { id: "pl131", name: "AKO BICOL", party: "AKO BICOL POLITICAL PARTY" },
      { id: "pl132", name: "GP (GALING SA PUSO)", party: "GALING SA PUSO PARTY-LIST" },
      { id: "pl133", name: "KAUNLAD PINOY", party: "KAISIPANG POSITIBO PARA SA KAUNLARAN NG PILIPINO" },
      { id: "pl134", name: "ABP", party: "ANG BUMBERO NG PILIPINAS" },
      { id: "pl135", name: "CWS", party: "CONSTRUCTION WORKERS SOLIDARITY INC." },
      { id: "pl136", name: "LPGMA", party: "LPG MARKETERS ASSOCIATION, INC." },
      { id: "pl137", name: "A TEACHER", party: "ADVOCACY FOR TEACHER EMPOWERMENT THROUGH ACTION COOPERATION AND HARMONY TOWARDS EDUCATIONAL REFORM" },
      { id: "pl138", name: "SWERTE", party: "SOLO PARENT WORKING FOR ECONOMIC RIGHTS AND OTHER THRUSTS FOR EQUALITY" },
      { id: "pl139", name: "GABAY", party: "GABAY UGNAYAN PARA SA REPORMA AT OPORTUNIDAD" },
      { id: "pl140", name: "MALASAKIT@BAYANIHAN", party: "MALASAKIT AT BAYANIHAN FOUNDATION, INC." },
      { id: "pl141", name: "AKAY NI SOL", party: "AKAY NI SOLUSYON ORGANISASYON AT LABAN" },
      { id: "pl142", name: "LUNAS", party: "LUNGSOD AASENSO" },
      { id: "pl143", name: "DIWA", party: "DEMOCRATIC INDEPENDENT WORKERS ASSOCIATION" },
      { id: "pl144", name: "PINUNO", party: "PINATATAG NA UGNAYAN PARA SA MGA OPORTUNIDAD SA PABAHAY NG MASA" },
      { id: "pl145", name: "PAMILYA MUNA", party: "ANG PAMILYA MUNA" },
      { id: "pl146", name: "BAGONG PILIPINAS", party: "BAGONG MAUNLAD NA PILIPINAS" },
      { id: "pl147", name: "HUGPONG FEDERAL", party: "HUGPONG FEDERAL MOVEMENT OF THE PHILIPPINES, INC." },
      { id: "pl148", name: "TUPAD", party: "TUPAD" },
      { id: "pl149", name: "LANG KAWAL", party: "LAANG KAWAL NG PILIPINAS" },
      { id: "pl150", name: "PAMILYA KO", party: "PAMILYA KO" },
      { id: "pl151", name: "BBM", party: "BANGON BAGONG MINERO" },
      { id: "pl152", name: "HEAL PH", party: "HEALTH ALLIANCE PH" },
      { id: "pl153", name: "ABANG LINGKOD", party: "ABANG LINGKOD INC." },
      { id: "pl154", name: "MAGSASAKA", party: "MAGKAKASAMA SA SAKAHAN, KAUNLARAN" },
      { id: "pl155", name: "MAHARLIKA", party: "MAHARLIKANG PILIPINO PARTY" },
      { id: "pl156", name: "USWAG ILONGGO", party: "USWAG ILONGGO PARTY" }
    ]
  }
];
