
import { Candidate } from '../positions';

export const partyListCandidates: Candidate[] = [
  { id: "pl1", name: "4PS", party: "PAGTIBAYIN AT PALAGUIN ANG PANGKABUHAYANG PILIPINO" },
  { id: "pl2", name: "PPP", party: "PUWERSA NG PILIPINONG PANDAGAT" },
  { id: "pl3", name: "FPJ PANDAY BAYANIHAN", party: "FPJ PANDAY BAYANIHAN PARTYLIST" },
  { id: "pl4", name: "KABATAAN", party: "KABATAAN PARTYLIST" },
  { id: "pl5", name: "DUTERTE YOUTH", party: "DUTY TO ENERGIZE THE REPUBLIC THROUGH THE ENLIGHTENMENT OF THE YOUTH" },
  { id: "pl6", name: "ML", party: "MAMAMAYANG LIBERAL" },
  { id: "pl7", name: "PBBM", party: "PILIPINAS BABANGON MULI" },
  { id: "pl8", name: "P3PWD", party: "KOMUNIDAD NG PAMILYA PASYENTE AT PERSONS WITH DISABILITIES" },
  { id: "pl9", name: "MURANG KURYENTE", party: "MURANG KURYENTE PARTYLIST" },
  { id: "pl10", name: "BICOL SARO", party: "BICOL SARO" },
  { id: "pl11", name: "IPATUPAD", party: "IPATUPAD FOR WORKERS, INC." },
  { id: "pl12", name: "PATROL", party: "PUBLIC SAFETY ALLIANCE FOR TRANSFORMATION AND RULE OF LAW, INC." },
  { id: "pl13", name: "JUAN PINOY", party: "JUAN-PINAGKAISANG ORDINARYONG MAMAMAYAN PARA YUMABONG" },
  { id: "pl14", name: "ARTE", party: "ADVOCATES FOR RETAIL, FASHION, TEXTILE, TRADITION, EVENTS & AND CREATIVE SERVICES SECTOR" },
  { id: "pl15", name: "WIFI", party: "WALANG IWANAN SA FREE INTERNET, INC." },
  { id: "pl16", name: "MAAGAP", party: "MOVEMENT OF ACTIVE APOSTOLIC GUARDIANS ASSOCIATION OF THE PHILIPPINES" },
  { id: "pl17", name: "UNITED SENIOR CITIZENS", party: "UNITED SENIOR CITIZENS KOALITION NG PILIPINAS" },
  { id: "pl18", name: "EPANAW SAMBAYANAN", party: "MINDANAO INDIGENOUS PEOPLES CONFERENCE FOR PEACE AND DEVELOPMENT" },
  { id: "pl19", name: "AKO PADAYON", party: "AKO PADAYON PILIPINO PARTYLIST" },
  { id: "pl20", name: "TUCP", party: "TRADE UNION CONGRESS PARTY" },
  { id: "pl21", name: "ACT TEACHERS", party: "ACT TEACHERS PARTY-LIST" },
  { id: "pl22", name: "1PACMAN", party: "ONE PATRIOTIC COALITION OF MARGINALIZED NATIONALS INC." },
  { id: "pl23", name: "TGP", party: "TALINO AT GALING NG PINOY" },
  { id: "pl24", name: "DUMPER PTDA", party: "DUMPER PHILIPPINES TAXI DRIVERS ASSOCIATION, INC." },
  { id: "pl25", name: "ANAKALUSUGAN", party: "ALAGAAN NATIN ATING KALUSUGAN INC." },
  { id: "pl26", name: "AKSYON DAPAT", party: "AKSYON DAPAT INCORPORATED" },
  { id: "pl27", name: "BHW", party: "BARANGAY HEALTH WELLNESS" },
  { id: "pl28", name: "SULONG DIGNIDAD", party: "SULONG DIGNIDAD REGIONAL POLITICAL PARTY" },
  { id: "pl29", name: "BATANG QUIAPO", party: "SULONG MGA BATANG QUIAPO" },
  { id: "pl30", name: "PBA", party: "PWERSA NG BAYANING ATLETA" },
  { id: "pl31", name: "GILAS", party: "GENERASYONG INIAALAY LAGI ANG SARILI" },
  { id: "pl32", name: "AKO ILOCANO AKO", party: "AKO ILOCANO AKO" },
  { id: "pl33", name: "PAMILYANG MAGSASAKA", party: "PAMILYANG MAGSASAKA" },
  { id: "pl34", name: "CLICK PARTY", party: "COMPUTER LITERACY INNOVATION CONNECTIVITY AND KNOWLEDGE" },
  { id: "pl35", name: "ABANTE BISDAK", party: "ABANTE BISDAK" },
  { id: "pl36", name: "MANILA TEACHERS", party: "MANILA TEACHERS' SAVINGS AND LOAN ASSOCIATION, INC." },
  { id: "pl37", name: "PAMANA", party: "IBALIK ANG KULTURANG PAMANA MOVEMENT" },
  { id: "pl38", name: "NANAY", party: "NANAY" },
  { id: "pl39", name: "KM NGAYON NA", party: "KILOS MAMAMAYAN NGAYON NA" },
  { id: "pl40", name: "BABAE AKO", party: "BABAE AKO PARA SA BAYAN INC." },
  { id: "pl41", name: "ARISE", party: "ALLIANCE FOR RESILIENCE SUSTAINABILITY AND EMPOWERMENT" },
  { id: "pl42", name: "MAGDALO", party: "MAGDALO PARA SA PILIPINO" },
  { id: "pl43", name: "APEC", party: "ASSOCIATION OF PHILIPPINE ELECTRIC COOPERATIVES" },
  { id: "pl44", name: "MAGBUBUKID", party: "MAMAMAYAN PARA SA GOBYERNONG BUBUKLOD SA MGA ISIP AT DIWA NG MGA PILIPINO" },
  { id: "pl45", name: "SSS-GSIS PENSYONADO", party: "SSS-GSIS PENSYONADO" },
  { id: "pl46", name: "GABRIELA", party: "GABRIELA WOMEN'S PARTY" },
  { id: "pl47", name: "TINGOG", party: "TINGOG SINIRANGAN" },
  { id: "pl48", name: "APAT-DAPAT", party: "ANG PROGRAMANG AASENSO TAUMBAYAN - DREAM, ACT, PARTICIPATE, ADVOCATE FOR SUSTAINABLE TRANSFORMATION" },
  { id: "pl49", name: "AHON MAHIRAP", party: "AHON MAHIRAP" },
  { id: "pl50", name: "UGB", party: "UNYON NG MGA GABAY NG BAYAN" },
  { id: "pl51", name: "AKBAYAN", party: "AKBAYAN CITIZENS' ACTION PARTY" },
  { id: "pl52", name: "AGIMAT", party: "AGIMAT NG MASA" },
  { id: "pl53", name: "PHILRECA", party: "PHILIPPINE RURAL ELECTRIC COOPERATIVES ASSOCIATION, INC." },
  { id: "pl54", name: "KAPUSO PM", party: "KABALIKAT PATUNGO SA UMUUNLAD NA SISTEMATIKO AT ORGANISADONG PANGKABUHAYAN" },
  { id: "pl55", name: "ILOCANO DEFENDERS", party: "ILOCANO DEFENDERS INC." },
  { id: "pl56", name: "1-RIDER PARTY-LIST", party: "ANG BUKLOD NG MGA MOTORISTA NG PILIPINAS" },
  { id: "pl57", name: "TICTOK", party: "TULONG IPAMAHAGI SA COMMUNIDAD TUNGO ONSA KAUNLARAN" },
  { id: "pl58", name: "WAGE HIKE", party: "PARTIDO TRABAHO AT WAGE HIKE" },
  { id: "pl59", name: "BAYAN MUNA", party: "BAYAN MUNA" },
  { id: "pl60", name: "ANG PROBINSIYANO", party: "ALYANSA NG MGA MAMAMAYANG PROBINSIYANO" },
  { id: "pl61", name: "BANAT", party: "BANAT BARANGAY NATIN" },
  { id: "pl62", name: "SBP", party: "SERBISYO SA BAYAN PARTY" },
  { id: "pl63", name: "BUHAY", party: "BUHAY HAYAAN YUMABONG" },
  { id: "pl64", name: "TULUNGAN TAYO", party: "TULUNGAN TAYO" },
  { id: "pl65", name: "SAGIP", party: "SOCIAL AMELIORATION & GENUINE INTERVENTION ON POVERTY" },
  { id: "pl66", name: "BTS", party: "BAYANING TSUPER BAYANING TSUPER" },
  { id: "pl67", name: "VENDORS", party: "VENDOR SAMAHAN NG MGA MANININDANG PILIPINO" },
  { id: "pl68", name: "ACT-CIS", party: "ANTI-CRIME AND TERRORISM - COMMUNITY INVOLVEMENT AND SUPPORT, INC." },
  { id: "pl69", name: "AKTIBONG KAAGAPAY", party: "AKTIBONG KAAGAPAY NG MGA MANGGAGAWA" },
  { id: "pl70", name: "ASENSO PINOY", party: "ASENSO PINOY" },
  { id: "pl71", name: "SOLO PARENTS", party: "SOLO PARENTS" },
  { id: "pl72", name: "ANG KOMADRONA", party: "ANG KOMADRONA INC." },
  { id: "pl73", name: "PROMDI", party: "ABAG PROMDI" },
  { id: "pl74", name: "PUSONG PINOY", party: "PUSONG PINOY" },
  { id: "pl75", name: "KUSUG TAUSUG", party: "KUSUG TAUSUG" },
  { id: "pl76", name: "DAMAYANG FILIPINO", party: "DAMAYANG FILIPINO MOVEMENT, INCORPORATED" },
  { id: "pl77", name: "MPBL", party: "MAHARLIKANG PILIPINO SA BAGONG LIPUNAN" },
  { id: "pl78", name: "ANGAT AKMA AT TAMA", party: "ANG ATMA AT TAMA" },
  { id: "pl79", name: "KALINGA", party: "ADVOCACY FOR SOCIAL EMPOWERMENT AND NATION" },
  { id: "pl80", name: "BOSES PARTY-LIST", party: "BOSES PARTY-LIST" },
  { id: "pl81", name: "ARANGKADA PILIPINO", party: "ARANGKADA PILIPINO" },
  { id: "pl82", name: "AANGAT TAYO", party: "AANGAT TAYO PARTYLIST" },
  { id: "pl83", name: "OFW", party: "ONE FILIPINOS WORLDWIDE PARTYLIST" },
  { id: "pl84", name: "BIDA KATAGUMPAY", party: "BAYAN ITAYO ANG DANGAL NG AGRIKULTURA KASAMA SA TAGUMPAY" },
  { id: "pl85", name: "KAMANGGAGAWA", party: "KAMPIHAN NG MGA MARALITA AT MANGGAGAWA" },
  { id: "pl86", name: "BFF", party: "BALIKATAN OF FILIPINO FAMILIES" },
  { id: "pl87", name: "BUNYOG", party: "BUNYOG (PAGKAKAISA)" },
  { id: "pl88", name: "AGRI", party: "AGRI-AGRA NA REPORMA PARA SA MAGSASAKA NG PILIPINAS" },
  { id: "pl89", name: "SENIOR CITIZENS", party: "COALITION OF ASSOCIATIONS OF SENIOR CITIZENS IN THE PHILIPPINES" },
  { id: "pl90", name: "4K", party: "KABABAIHAN KABALIKATAN PARA SA KAPAKANAN AT KAUNLARAN NG BAYAN" },
  { id: "pl91", name: "PBP", party: "PARTIDO SA BAG-ONG PILIPINO" },
  { id: "pl92", name: "ONE COOP", party: "AURORA INTEGRATED MULTI-PURPOSE COOPERATIVE (AIMCOOP)" },
  { id: "pl93", name: "CIBAC", party: "CITIZENS' BATTLE AGAINST CORRUPTION" },
  { id: "pl94", name: "BH - BAGONG HENERASYON", party: "BAGONG HENERASYON" },
  { id: "pl95", name: "1AGILA", party: "1 AGILA-ALALAYANG AGILA PARA SA BAYAN, INC." },
  { id: "pl96", name: "EDUAKSYON", party: "EDUAKSYON" },
  { id: "pl97", name: "ANG TINIG NG SENIORS", party: "ANG TINIG NG SENIOR CITIZENS SA FILIPINAS, INC." },
  { id: "pl98", name: "BG PARTY-LIST", party: "BISAYA GYUD PARTY-LIST" },
  { id: "pl99", name: "PINOY AKO", party: "PINOY AKO" },
  { id: "pl100", name: "H.E.L.P. PILIPINAS", party: "HEALTH, EDUCATION, LIVELIHOOD PROGRAM OF THE PHILIPPINES" },
  { id: "pl101", name: "HEALTH WORKERS", party: "HEALTH WORKERS PARTY-LIST" },
  { id: "pl102", name: "PEOPLE'S CHAMP", party: "PEOPLES CHAMP GUARDIANS PARTYLIST" },
  { id: "pl103", name: "AA-KASOSYO PARTY", party: "KASOSYO PRODUCER-CONSUMER EXCHANGE ASSOCIATION, INC." },
  { id: "pl104", name: "SOLID NORTH PARTY", party: "SOLIDARITY OF NORTHERN LUZON PEOPLE'S PARTY" },
  { id: "pl105", name: "ABAMIN", party: "ABANTE MINDANAO, INC." },
  { id: "pl106", name: "TRABAHO", party: "TAGAPAGTAGUYOD NG MGA REPORMA AT ADHIKAING BABALIKAT AT HAHANGO SA MGA OPORTUNIDAD PARA SA MGA PILIPINO" },
  { id: "pl107", name: "ANGKASANGGA", party: "ANG KASANGGA NG MANGUNGUMA - OWA MANGUNGUMA" },
  { id: "pl108", name: "TODA", party: "AKSYON TOWARDS DEVELOPMENT AND ACTION" },
  { id: "pl109", name: "TURISMO", party: "TURISMO ISULONG MO" },
  { id: "pl110", name: "ABONO", party: "ABONO PARTYLIST" },
  { id: "pl111", name: "ASAP NA", party: "ALYANSA LABAN SA SUBSTANCE ABUSE PARA SA BAGONG PILIPINAS NATIN" },
  { id: "pl112", name: "LINGAP", party: "LIGA NG NAGKAKAISANG MAHIHIRAP" },
  { id: "pl113", name: "UNITED FRONTLINERS", party: "UNITED FRONTLINERS OF THE PHILIPPINES" },
  { id: "pl114", name: "KASAMBAHAY", party: "KASAMBAHAY TAYO, INC." },
  { id: "pl115", name: "TUTOK TO WIN", party: "TUTOK TO WIN" },
  { id: "pl116", name: "AKO OFW", party: "ADVOCATES & KEEPERS ORGANISASYON & LABAN" },
  { id: "pl117", name: "AGAP", party: "AGRICULTURAL SECTOR ALLIANCE OF THE PHILIPPINES" },
  { id: "pl118", name: "1TAHANAN", party: "1TAHANAN INC." },
  { id: "pl119", name: "COOP-NATCCO", party: "COOPERATIVE NATCCO NETWORK PARTY" },
  { id: "pl120", name: "KABAYAN", party: "KABALIKAT NG MAMAMAYAN" },
  { id: "pl121", name: "1MUNTI", party: "1MUNTI" },
  { id: "pl122", name: "PINOY WORKERS", party: "PEOPLE WORKING FOR THE DEVELOPMENT OF THE PHILIPPINES" },
  { id: "pl123", name: "API PARTY", party: "ABANTE PANGASINAN - ILOKANO PARTY" },
  { id: "pl124", name: "AKO BISAYA", party: "AKO BISAYA INC." },
  { id: "pl125", name: "KAMALAYAN", party: "KALIPUNAN NG MARALITA AT MALAYANG MAMAMAYA, INC." },
  { id: "pl126", name: "AKO TANOD", party: "AKO TANOD INCORPORATED" },
  { id: "pl127", name: "PROBINSYANO AKO", party: "PROBINSYANO AKO" },
  { id: "pl128", name: "KABABAIHAN", party: "HANAY NG MGA KABABAIHAN AT KANILANG MGA KASANGGA SA LIPUNAN" },
  { id: "pl129", name: "RAM", party: "REBOLUSONARYONG ALYANSANG MAKABANSA" },
  { id: "pl130", name: "ALONA", party: "ALLIANCE OF ORGANIZATIONS, NETWORKS, AND ASSOCIATIONS OF THE PHILIPPINES" },
  { id: "pl131", name: "AKO BICOL", party: "AKO BICOL POLITICAL PARTY" },
  { id: "pl132", name: "GP (GALING SA PUSO)", party: "GALING SA PUSO PARTY-LIST" },
  { id: "pl133", name: "KAUNLAD PINOY", party: "KAISIPANG POSITIBO PARA SA KAUNLARAN NG PILIPINO" },
  { id: "pl134", name: "ABP", party: "ANG BUMBERO NG PILIPINAS" },
  { id: "pl135", name: "CWS", party: "CONSTRUCTION WORKERS SOLIDARITY INC." },
  { id: "pl136", name: "LPGMA", party: "LPG MARKETERS ASSOCIATION, INC." },
  { id: "pl137", name: "A TEACHER", party: "ADVOCACY FOR TEACHER EMPOWERMENT THROUGH ACTION COOPERATION AND HARMONY TOWARDS EDUCATIONAL REFORM" },
  { id: "pl138", name: "SWERTE", party: "SOLO PARENT WORKING FOR ECONOMIC RIGHTS AND OTHER THRUSTS FOR EQUALITY" },
  { id: "pl139", name: "GABAY", party: "GABAY UGNAYAN PARA SA REPORMA AT OPORTUNIDAD" },
  { id: "pl140", name: "MALASAKIT@BAYANIHAN", party: "MALASAKIT AT BAYANIHAN FOUNDATION, INC." },
  { id: "pl141", name: "AKAY NI SOL", party: "AKAY NI SOLUSYON ORGANISASYON AT LABAN" },
  { id: "pl142", name: "LUNAS", party: "LUNGSOD AASENSO" },
  { id: "pl143", name: "DIWA", party: "DEMOCRATIC INDEPENDENT WORKERS ASSOCIATION" },
  { id: "pl144", name: "PINUNO", party: "PINATATAG NA UGNAYAN PARA SA MGA OPORTUNIDAD SA PABAHAY NG MASA" },
  { id: "pl145", name: "PAMILYA MUNA", party: "ANG PAMILYA MUNA" },
  { id: "pl146", name: "BAGONG PILIPINAS", party: "BAGONG MAUNLAD NA PILIPINAS" },
  { id: "pl147", name: "HUGPONG FEDERAL", party: "HUGPONG FEDERAL MOVEMENT OF THE PHILIPPINES, INC." },
  { id: "pl148", name: "TUPAD", party: "TUPAD" },
  { id: "pl149", name: "LANG KAWAL", party: "LAANG KAWAL NG PILIPINAS" },
  { id: "pl150", name: "PAMILYA KO", party: "PAMILYA KO" },
  { id: "pl151", name: "BBM", party: "BANGON BAGONG MINERO" },
  { id: "pl152", name: "HEAL PH", party: "HEALTH ALLIANCE PH" },
  { id: "pl153", name: "ABANG LINGKOD", party: "ABANG LINGKOD INC." },
  { id: "pl154", name: "MAGSASAKA", party: "MAGKAKASAMA SA SAKAHAN, KAUNLARAN" },
  { id: "pl155", name: "MAHARLIKA", party: "MAHARLIKANG PILIPINO PARTY" },
  { id: "pl156", name: "USWAG ILONGGO", party: "USWAG ILONGGO PARTY" }
];
