
import { Candidate } from '../positions';

export const senatorCandidates: Candidate[] = [
  { id: "s1", name: "ABALOS, BENHUR (PFP)", party: "PARTIDO FEDERAL NG PILIPINAS" },
  { id: "s2", name: "ACOSTA, JEROME (MKBYN)", party: "MAKABAYANG KOALISYON NG MAMAMAYAN" },
  { id: "s3", name: "AMAD, WILSON (IND)", party: "INDEPENDENT" },
  { id: "s4", name: "ANDAMO, NARS ALYN (MKBYN)", party: "MAKABAYANG KOALISYON NG MAMAMAYAN" },
  { id: "s5", name: "AQUINO, BAM (LP)", party: "LIBERAL PARTY" },
  { id: "s6", name: "ARAMBULO, RONNEL (MKBYN)", party: "MAKABAYANG KOALISYON NG MAMAMAYAN" },
  { id: "s7", name: "BALLON, ROBERTO (IND)", party: "INDEPENDENT" },
  { id: "s8", name: "BINAY, ABBY (NPC)", party: "NATIONALIST PEOPLE'S COALITION" },
  { id: "s9", name: "BONDOC, JIMMY (PDPLBN)", party: "PARTIDO DEMOKRATIKO PILIPINO LAKAS NG BAYAN" },
  { id: "s10", name: "BONG REVILLA, RAMON JR. (LAKAS)", party: "LAKAS-CHRISTIAN MUSLIM DEMOCRATS" },
  { id: "s11", name: "BOSITA, BONIFACIO (IND)", party: "INDEPENDENT" },
  { id: "s12", name: "BROSAS, ARLENE (MKBYN)", party: "MAKABAYANG KOALISYON NG MAMAMAYAN" },
  { id: "s13", name: "CABONEGRO, ROY (DPP)", party: "DEMOCRATIC PARTY OF THE PHILIPPINES" },
  { id: "s14", name: "CAPUYAN, ALLEN (PPP)", party: "PARTIDO NG PAGBABAGO NG PILIPINO" },
  { id: "s15", name: "CASIÑO, TEDDY (MKBYN)", party: "MAKABAYANG KOALISYON NG MAMAMAYAN" },
  { id: "s16", name: "CASTRO, TEACHER FRANCE (MKBYN)", party: "MAKABAYANG KOALISYON NG MAMAMAYAN" },
  { id: "s17", name: "CAYETANO, PIA (NPC)", party: "NATIONALIST PEOPLE'S COALITION" },
  { id: "s18", name: "CAYETANO, PIA (IND)", party: "INDEPENDENT" },
  { id: "s19", name: "D'ANGELO, DAVID (BUNYOG)", party: "BUNYOG" },
  { id: "s20", name: "DE ALBAN, ATTORNEY ANGELO (IND)", party: "INDEPENDENT" },
  { id: "s21", name: "DE GUZMAN, KA LEODY (PLM)", party: "PARTIDO LAKAS NG MASA" },
  { id: "s22", name: "DELA ROSA, BATO (PDPLBN)", party: "PARTIDO DEMOKRATIKO PILIPINO LAKAS NG BAYAN" },
  { id: "s23", name: "DOMINGO, NANAY MIMI (MKBYN)", party: "MAKABAYANG KOALISYON NG MAMAMAYAN" },
  { id: "s24", name: "ESCOBAL, ARNEL (PM)", party: "PARTIDO MANGGAGAWA" },
  { id: "s25", name: "ESPIRITU, LUKE (PLM)", party: "PARTIDO LAKAS NG MASA" },
  { id: "s26", name: "FLORANDA, MODY PISTON (MKBYN)", party: "MAKABAYANG KOALISYON NG MAMAMAYAN" },
  { id: "s27", name: "GO, BONG GO (PDPLBN)", party: "PARTIDO DEMOKRATIKO PILIPINO LAKAS NG BAYAN" },
  { id: "s28", name: "GONZALES, NORBERTO (PDSP)", party: "PARTIDO DEMOKRATIKO SOSYALISTA NG PILIPINAS" },
  { id: "s29", name: "HINLO, JAYVEE (PDPLBN)", party: "PARTIDO DEMOKRATIKO PILIPINO LAKAS NG BAYAN" },
  { id: "s30", name: "HONTIVEROS, RISA (AKBAYAN)", party: "AKBAYAN CITIZENS' ACTION PARTY" },
  { id: "s31", name: "LACSON, PING (IND)", party: "INDEPENDENT" },
  { id: "s32", name: "LAMBINO, RAUL (PDPLBN)", party: "PARTIDO DEMOKRATIKO PILIPINO LAKAS NG BAYAN" },
  { id: "s33", name: "LAPID, LITO (NPC)", party: "NATIONALIST PEOPLE'S COALITION" },
  { id: "s34", name: "LEE, MANOY WILBERT (AKSYON)", party: "AKSYON DEMOKRATIKO" },
  { id: "s35", name: "LIDASAN, AMIRAH (MKBYN)", party: "MAKABAYANG KOALISYON NG MAMAMAYAN" },
  { id: "s36", name: "LOPEZ, BETH (IND)", party: "INDEPENDENT" },
  { id: "s37", name: "MARCOS, IMEE R. (NP)", party: "NACIONALISTA PARTY" },
  { id: "s38", name: "MARQUEZ, NORMAN (IND)", party: "INDEPENDENT" },
  { id: "s39", name: "MATULA, ATTY. SONNY (WPP)", party: "WORKERS' AND PEASANTS' PARTY" },
  { id: "s40", name: "MAZA, LIZA (MKBYN)", party: "MAKABAYANG KOALISYON NG MAMAMAYAN" },
  { id: "s41", name: "MENDOZA, JEED (IND)", party: "INDEPENDENT" },
  { id: "s42", name: "MONTEMAYOR, JOCEY (IND)", party: "INDEPENDENT" },
  { id: "s43", name: "MUSTAPHA, SUBAIR (WPP)", party: "WORKERS' AND PEASANTS' PARTY" },
  { id: "s44", name: "ONG, DOC WILLIE (AKSYON)", party: "AKSYON DEMOKRATIKO" },
  { id: "s45", name: "PACQUIAO, MANNY PACMAN (PFP)", party: "PARTIDO FEDERAL NG PILIPINAS" },
  { id: "s46", name: "PANGILINAN, KIKO (LP)", party: "LIBERAL PARTY" },
  { id: "s47", name: "QUIBOLOY, APOLLO (IND)", party: "INDEPENDENT" },
  { id: "s48", name: "SALDUA, DING (IND)", party: "INDEPENDENT" },
  { id: "s49", name: "SILBIDO, BEN REYES (IND)", party: "INDEPENDENT" },
  { id: "s50", name: "SOTTO, TITO (NPC)", party: "NATIONALIST PEOPLE'S COALITION" },
  { id: "s51", name: "TAPANG, MICHAEL BONGBONG (PVL)", party: "PARTIDO NG VALENCIA LOOB" },
  { id: "s52", name: "TULFO, BEN BITAG (IND)", party: "INDEPENDENT" },
  { id: "s53", name: "TULFO, ERWIN RAFFY ERAP (IND)", party: "INDEPENDENT" },
  { id: "s54", name: "VALERA, MARI MAR (IND)", party: "INDEPENDENT" },
  { id: "s55", name: "VILLALUZ, CAMILLE (PV)", party: "PARTIDO NG VALENCIA" },
  { id: "s56", name: "VILLEGAS, LEANDRO (IND)", party: "INDEPENDENT" }
];
