
import { Candidate } from '../positions';

export const senatorCandidates: Candidate[] = [
  { id: "s1", name: "ABALOS, BENHUR", party: "PFP" },
  { id: "s2", name: "ACERON, JOVILYN", party: "IND" },
  { id: "s3", name: "ACLAN, KUYA", party: "IND" },
  { id: "s4", name: "ACOPIADO, MERCEDITA", party: "IND" },
  { id: "s5", name: "ADONIS, JEROME", party: "MKBYN" },
  { id: "s6", name: "ADORABLE, ABEL", party: "IND" },
  { id: "s7", name: "ADVINCULA, DINGBICOL", party: "IND" },
  { id: "s8", name: "ADVINCULA, PETER JOEMEL", party: "IND" },
  { id: "s9", name: "AGAD, ROBERT", party: "IND" },
  { id: "s10", name: "AGUILAR, CEZ", party: "WPP" },
  { id: "s11", name: "ALCANTARA, ERIC", party: "IND" },
  { id: "s12", name: "AMAD, WILSON", party: "IND" },
  { id: "s13", name: "AMIR HUSSIN, SALIPADA", party: "PM" },
  { id: "s14", name: "ANCAJAS, NELSON", party: "IND" },
  { id: "s15", name: "ANDAMO, NARS ALYN", party: "MKBYN" },
  { id: "s16", name: "ANDRADA, KUYA MANNY", party: "IND" },
  { id: "s17", name: "ANDRINO, BOBIE", party: "IND" },
  { id: "s18", name: "APOLINARIO, JOEL", party: "PM" },
  { id: "s19", name: "AQUINO, BAM", party: "KNP" },
  { id: "s20", name: "AQUINO, PRIMO", party: "IND" },
  { id: "s21", name: "ARAMBULO, RONNEL", party: "MKBYN" },
  { id: "s22", name: "ARCEGA, GERALD", party: "PM" },
  { id: "s23", name: "ARELLANO, ERNESTO", party: "KTPNAN" },
  { id: "s24", name: "ARES, JERSON", party: "IND" },
  { id: "s25", name: "ARGUELLES, RICARDA", party: "IND" },
  { id: "s26", name: "ARTAJO, ADAM", party: "IND" },
  { id: "s27", name: "BAJO, ISMAEL", party: "IND" },
  { id: "s28", name: "BALITE, KAKA", party: "IND" },
  { id: "s29", name: "BALLON, ROBERTO", party: "IND" },
  { id: "s30", name: "BALMAS, JAIME", party: "KBL" },
  { id: "s31", name: "BANOSAN, LORETO", party: "IND" },
  { id: "s32", name: "BASILAN, RODOLFO", party: "IND" },
  { id: "s33", name: "BAUTISTA, EDUARDO", party: "IND" },
  { id: "s34", name: "BENIGA, ELVIS", party: "IND" },
  { id: "s35", name: "BIAZON, DAVE", party: "IND" },
  { id: "s36", name: "BILLONES, MARIA CHARITO", party: "IND" },
  { id: "s37", name: "BINAY, ABBY", party: "NPC" },
  { id: "s38", name: "BONAYOG, CHITO", party: "IND" },
  { id: "s39", name: "BONDOC, JIMMY", party: "PDPLBN" },
  { id: "s40", name: "BONG REVILLA,RAMON, JR.", party: "LAKAS" },
  { id: "s41", name: "BOSITA, BONIFACIO", party: "IND" },
  { id: "s42", name: "BOVIER, WARLY", party: "IND" },
  { id: "s43", name: "BROSAS, ARLENE", party: "MKBYN" },
  { id: "s44", name: "BRUCE, HERNANDO", party: "IND" },
  { id: "s45", name: "BUNAYOG, INJIM", party: "IND" },
  { id: "s46", name: "BUNILLA, JOSE", party: "IND" },
  { id: "s47", name: "CABALIDA, JUNE KING SBC", party: "IND" },
  { id: "s48", name: "CABONEGRO, ROY", party: "DPP" },
  { id: "s49", name: "CADION, LEO", party: "IND" },
  { id: "s50", name: "CAPUNO, ONDONG", party: "IND" },
  { id: "s51", name: "CAPUYAN, ALLEN", party: "PPP" },
  { id: "s52", name: "CASIMRA, KHALED", party: "IND" },
  { id: "s53", name: "CASIÑO, TEDDY", party: "MKBYN" },
  { id: "s54", name: "CASIPONG, AGAPITO", party: "IND" },
  { id: "s55", name: "CASTRO, TEACHER FRANCE", party: "MKBYN" },
  { id: "s56", name: "CATURAN, MIG", party: "IND" },
  { id: "s57", name: "CAUSING, BERTENI", party: "BUNYOG" },
  { id: "s58", name: "CAY, LAUREL", party: "KKK" },
  { id: "s59", name: "CAYETANO, PIA", party: "NP" },
  { id: "s60", name: "CHACLAG, GABRIEL", party: "IND" },
  { id: "s61", name: "CHAN, DAVID PAUL", party: "IND" },
  { id: "s62", name: "CHAN, EMILIO", party: "IND" },
  { id: "s63", name: "CHICO, RAFFY", party: "PM" },
  { id: "s64", name: "CUATCHIN, SHIRLY", party: "WPP" },
  { id: "s65", name: "D'ANGELO, DAVID", party: "BUNYOG" },
  { id: "s66", name: "DE ALBAN,ATTORNEY ANGELO", party: "IND" },
  { id: "s67", name: "DE GUZMAN, KA LEODY", party: "PLM" },
  { id: "s68", name: "DE GUZMAN, ORLANDO", party: "IND" },
  { id: "s69", name: "DELA ROSA, BATO", party: "PDPLBN" },
  { id: "s70", name: "DELGADO, JOSEPH", party: "IND" },
  { id: "s71", name: "DELOS REYES, PHIL", party: "IND" },
  { id: "s72", name: "DIAZ, DING", party: "PPP" },
  { id: "s73", name: "DITANONGUN, SUNANG", party: "IND" },
  { id: "s74", name: "DOMAGTOY, GEM", party: "IND" },
  { id: "s75", name: "DOMINGO, KA SONNY", party: "IND" },
  { id: "s76", name: "DORINGO, NANAY MIMI", party: "MKBYN" },
  { id: "s77", name: "DUQUE, EDGARDO", party: "IND" },
  { id: "s78", name: "DY, JOSEPH", party: "IND" },
  { id: "s79", name: "ENCARNACION, ALEXANDER", party: "IND" },
  { id: "s80", name: "ERA, MARIA FE", party: "IND" },
  { id: "s81", name: "ESCOBAL, ARNEL", party: "PM" },
  { id: "s82", name: "ESCOBAR, JOHN", party: "IND" },
  { id: "s83", name: "ESPIRITU, LUKE", party: "PLM" },
  { id: "s84", name: "ESTRELLA, IDOLODI", party: "IND" },
  { id: "s85", name: "FLORANDA, MODY PISTON", party: "MKBYN" },
  { id: "s86", name: "GAMBOA, MARC LOUIE", party: "IND" },
  { id: "s87", name: "GARGARITA, JONRY", party: "IND" },
  { id: "s88", name: "GO, BONG GO", party: "PDPLBN" },
  { id: "s89", name: "GONZALES, NORBERTO", party: "PDSP" },
  { id: "s90", name: "GUIGAYUMA, JB", party: "KKK" },
  { id: "s91", name: "HINLO, JAYVEE", party: "PDPLBN" },
  { id: "s92", name: "HONASAN, GRINGO", party: "RP" },
  { id: "s93", name: "INTE, VICTOR", party: "IND" },
  { id: "s94", name: "JOSE, RELLY JR.", party: "KBL" },
  { id: "s95", name: "JUMALON, ALICE", party: "IND" },
  { id: "s96", name: "KOKKINARAS, BAE DALAN", party: "WPP" },
  { id: "s97", name: "LACSON, PING", party: "IND" },
  { id: "s98", name: "LAGARE, SIXTO", party: "IND" },
  { id: "s99", name: "LAGUE, ALEX", party: "IND" },
  { id: "s100", name: "LAMBINO, RAUL", party: "PDPLBN" },
  { id: "s101", name: "LAMOSTE, PRINCEDATU", party: "WPP" },
  { id: "s102", name: "LAPID, LITO", party: "NPC" },
  { id: "s103", name: "LEE, MANOY WILBERT", party: "AKSYON" },
  { id: "s104", name: "LIDASAN, AMIRAH", party: "MKBYN" },
  { id: "s105", name: "LOPEZ, BETH", party: "IND" },
  { id: "s106", name: "LUBARBIO, HAPPY", party: "IND" },
  { id: "s107", name: "LUCAÑAS, MELCHOR", party: "IND" },
  { id: "s108", name: "MACARAEG, ROMEO", party: "WPP" },
  { id: "s109", name: "MAGTIRA, DANIEL", party: "IND" },
  { id: "s110", name: "MAIQUEZ, FREDIE", party: "IND" },
  { id: "s111", name: "MALINAO, GETTER", party: "IND" },
  { id: "s112", name: "MANALO, MAGNO", party: "IND" },
  { id: "s113", name: "MAQUISO, ARTEMIO", party: "IND" },
  { id: "s114", name: "MARCOLETA, RODANTE", party: "IND" },
  { id: "s115", name: "MARCOS, FRANCIS LEO", party: "IND" },
  { id: "s116", name: "MARCOS, IMEE R.", party: "NP" },
  { id: "s117", name: "MARCOS TALLANO TAGEAN", party: "IND" },
  { id: "s118", name: "MARQUEZ, NORMAN", party: "IND" },
  { id: "s119", name: "MARTINEZ, ERIC", party: "IND" },
  { id: "s120", name: "MATA, DOC MARITES", party: "IND" },
  { id: "s121", name: "MATULA, ATTY. SONNY", party: "WPP" },
  { id: "s122", name: "MAZA, LIZA", party: "MKBYN" },
  { id: "s123", name: "MENDOZA, HEIDI", party: "IND" },
  { id: "s124", name: "MENDOZA, KA MARTIN", party: "IND" },
  { id: "s125", name: "MENIANO, LUTHER", party: "IND" },
  { id: "s126", name: "MONTEALTO, LIGTAS", party: "IND" },
  { id: "s127", name: "MONTEMAYOR, JOEY", party: "IND" },
  { id: "s128", name: "MUSTAPHA, SUBAIR", party: "WPP" },
  { id: "s129", name: "NEGAPATAN, ERIC", party: "IND" },
  { id: "s130", name: "NICOLAS, RICHARD", party: "KBL" },
  { id: "s131", name: "NOEL, REX", party: "IND" },
  { id: "s132", name: "OLIVAR, JOSE JESSIE", party: "IND" },
  { id: "s133", name: "OLONAN, HENRY", party: "WPP" },
  { id: "s134", name: "ONG, DOC WILLIE", party: "AKSYON" },
  { id: "s135", name: "ONGJOCO, OSCAR", party: "IND" },
  { id: "s136", name: "ORDIALES, PETE", party: "WPP" },
  { id: "s137", name: "PACQUIAO, MANNY PACMAN", party: "PFP" },
  { id: "s138", name: "PACQUIAO, ROEL", party: "IND" },
  { id: "s139", name: "PADILLA, JANICE", party: "IND" },
  { id: "s140", name: "PAGARAGAN, SUPER MAR", party: "PM" },
  { id: "s141", name: "PALIZA, NHELING", party: "IND" },
  { id: "s142", name: "PALOMARES, DIEGO JR.", party: "PM" },
  { id: "s143", name: "PANGILINAN, KIKO", party: "LP" },
  { id: "s144", name: "PAR, TONY", party: "IND" },
  { id: "s145", name: "PARTOSA, EULOGIO JR.", party: "IND" },
  { id: "s146", name: "PEREZ, EPIFANIO", party: "IND" },
  { id: "s147", name: "PIMENTEL, BONG BONG", party: "WPP" },
  { id: "s148", name: "PLAZA, RASTAMAN", party: "IND" },
  { id: "s149", name: "QUERUBIN, ARIEL PORFIRIO", party: "NP" },
  { id: "s150", name: "QUIBOLOY, APOLLO", party: "IND" },
  { id: "s151", name: "RAMOS, PRINCESS JADE", party: "IND" },
  { id: "s152", name: "RAMOS, DANILO", party: "MKBYN" },
  { id: "s153", name: "RED, KUYA WILY", party: "IND" },
  { id: "s154", name: "RED, RANDY", party: "IND" },
  { id: "s155", name: "RESTUM, RANDY", party: "IND" },
  { id: "s156", name: "REVILLAME, WILLIE WIL", party: "IND" },
  { id: "s157", name: "REYES, JAMES", party: "IND" },
  { id: "s158", name: "RICABLANCA, WILLIE", party: "IND" },
  { id: "s159", name: "RODRIGUEZ, ATTY. VIC", party: "IND" },
  { id: "s160", name: "ROSALES, ELPIDIO JR.", party: "KBL" },
  { id: "s161", name: "RUBI, EDMON", party: "IND" },
  { id: "s162", name: "SABIT, VIRGINIA", party: "IND" },
  { id: "s163", name: "SAHIDULLA, NUR-ANA", party: "IND" },
  { id: "s164", name: "SALAPANTAN, JIMMY", party: "IND" },
  { id: "s165", name: "SALIH, NAJAR", party: "PM" },
  { id: "s166", name: "SALVADOR, PHILLIP IPE", party: "PDPLBN" },
  { id: "s167", name: "SAN RAMON, MULO", party: "IND" },
  { id: "s168", name: "SANCHEZ, MELISSA", party: "IND" }
];
