
import { Candidate } from '../positions';

export const senatorCandidates: Candidate[] = [
  { id: "s1", name: "ABALOS, BENHUR (PFP)", party: "PARTIDO FEDERAL NG PILIPINAS" },
  { id: "s2", name: "ADONIS, JEROME (MKBYN)", party: "MAKABAYANG KOALISYON NG MAMAMAYAN" },
  { id: "s3", name: "AMAD, WILSON (IND)", party: "INDEPENDENT" },
  { id: "s4", name: "ANDAMO, NARS ALYN (MKBYN)", party: "MAKABAYANG KOALISYON NG MAMAMAYAN" },
  { id: "s5", name: "AQUINO, BAM (KNP)", party: "KOALISYON NG NAGKAKAISANG PILIPINO" },
  { id: "s6", name: "ARAMBULO, RONNEL (MKBYN)", party: "MAKABAYANG KOALISYON NG MAMAMAYAN" },
  { id: "s7", name: "ARELLANO, ERNESTO (KTPNAN)", party: "KATIPUNAN NG NAGKAKAISANG PILIPINO" },
  { id: "s8", name: "BALLON, ROBERTO (IND)", party: "INDEPENDENT" },
  { id: "s9", name: "BINAY, ABBY (NPC)", party: "NATIONALIST PEOPLE'S COALITION" },
  { id: "s10", name: "BONDOC, JIMMY (PDPLBN)", party: "PARTIDO DEMOKRATIKO PILIPINO LAKAS NG BAYAN" },
  { id: "s11", name: "BONG REVILLA, RAMON, JR. (LAKAS)", party: "LAKAS-CHRISTIAN MUSLIM DEMOCRATS" },
  { id: "s12", name: "BOSITA, COLONEL (IND)", party: "INDEPENDENT" },
  { id: "s13", name: "BROSAS, ARLENE (MKBYN)", party: "MAKABAYANG KOALISYON NG MAMAMAYAN" },
  { id: "s14", name: "CABONEGRO, ROY (DPP)", party: "DEMOCRATIC PARTY OF THE PHILIPPINES" },
  { id: "s15", name: "CAPUYAN, ALLEN (PPP)", party: "PARTIDO NG PAGBABAGO NG PILIPINO" },
  { id: "s16", name: "CASIÑO, TEDDY (MKBYN)", party: "MAKABAYANG KOALISYON NG MAMAMAYAN" },
  { id: "s17", name: "CASTRO, TEACHER FRANCE (MKBYN)", party: "MAKABAYANG KOALISYON NG MAMAMAYAN" },
  { id: "s18", name: "CAYETANO, PIA (NP)", party: "NACIONALISTA PARTY" },
  { id: "s19", name: "D'ANGELO, DAVID (BUNYOG)", party: "BUNYOG" },
  { id: "s20", name: "DE ALBAN, ATTORNEY ANGELO (IND)", party: "INDEPENDENT" },
  { id: "s21", name: "DE GUZMAN, KA LEODY (PLM)", party: "PARTIDO LAKAS NG MASA" },
  { id: "s22", name: "DELA ROSA, BATO (PDPLBN)", party: "PARTIDO DEMOKRATIKO PILIPINO LAKAS NG BAYAN" },
  { id: "s23", name: "DOMINGO, NANAY MIMI (MKBYN)", party: "MAKABAYANG KOALISYON NG MAMAMAYAN" },
  { id: "s24", name: "ESCOBAL, ARNEL (PM)", party: "PARTIDO MANGGAGAWA" },
  { id: "s25", name: "ESPIRITU, LUKE (PLM)", party: "PARTIDO LAKAS NG MASA" },
  { id: "s26", name: "FLORANDA, MODY PISTON (MKBYN)", party: "MAKABAYANG KOALISYON NG MAMAMAYAN" },
  { id: "s27", name: "GAMBOA, MARC LOUIE (IND)", party: "INDEPENDENT" },
  { id: "s28", name: "GO, BONG GO (PDPLBN)", party: "PARTIDO DEMOKRATIKO PILIPINO LAKAS NG BAYAN" },
  { id: "s29", name: "GONZALES, NORBERTO (PDSP)", party: "PARTIDO DEMOKRATIKO SOSYALISTA NG PILIPINAS" },
  { id: "s30", name: "HINLO, JAYVEE (PDPLBN)", party: "PARTIDO DEMOKRATIKO PILIPINO LAKAS NG BAYAN" },
  { id: "s31", name: "HONASAN, GRINGO (RP)", party: "REPORMA PARTY" },
  { id: "s32", name: "JOSE, RELLY JR. (KBL)", party: "KILUSANG BAGONG LIPUNAN" },
  { id: "s33", name: "LACSON, PING (IND)", party: "INDEPENDENT" },
  { id: "s34", name: "LAMBINO, RAUL (PDPLBN)", party: "PARTIDO DEMOKRATIKO PILIPINO LAKAS NG BAYAN" },
  { id: "s35", name: "LAPID, LITO (NPC)", party: "NATIONALIST PEOPLE'S COALITION" },
  { id: "s36", name: "LEE, MANOY WILBERT (AKSYON)", party: "AKSYON DEMOKRATIKO" },
  { id: "s37", name: "LIDASAN, AMIRAH (MKBYN)", party: "MAKABAYANG KOALISYON NG MAMAMAYAN" },
  { id: "s38", name: "MARCOLETA, RODANTE (IND)", party: "INDEPENDENT" },
  { id: "s39", name: "MARCOS, IMEE R. (NP)", party: "NACIONALISTA PARTY" },
  { id: "s40", name: "MARQUEZ, NORMAN (IND)", party: "INDEPENDENT" },
  { id: "s41", name: "MARTINEZ, ERIC (IND)", party: "INDEPENDENT" },
  { id: "s42", name: "MATA, DOC MARITES (IND)", party: "INDEPENDENT" },
  { id: "s43", name: "MATULA, ATTY. SONNY (WPP)", party: "WORKERS' AND PEASANTS' PARTY" },
  { id: "s44", name: "MAZA, LIZA (MKBYN)", party: "MAKABAYANG KOALISYON NG MAMAMAYAN" },
  { id: "s45", name: "MENDOZA, HEIDI (IND)", party: "INDEPENDENT" },
  { id: "s46", name: "MONTEMAYOR, JOEY (IND)", party: "INDEPENDENT" },
  { id: "s47", name: "MUSTAPHA, SUBAIR (WPP)", party: "WORKERS' AND PEASANTS' PARTY" },
  { id: "s48", name: "OLIVAR, JOSE JESSIE (IND)", party: "INDEPENDENT" },
  { id: "s49", name: "ONG, DOC WILLIE (AKSYON)", party: "AKSYON DEMOKRATIKO" },
  { id: "s50", name: "PACQUIAO, MANNY PACMAN (PFP)", party: "PARTIDO FEDERAL NG PILIPINAS" },
  { id: "s51", name: "PANGILINAN, KIKO (LP)", party: "LIBERAL PARTY" },
  { id: "s52", name: "QUERUBIN, ARIEL PORFIRIO (NP)", party: "NACIONALISTA PARTY" },
  { id: "s53", name: "QUIBOLOY, APOLLO (IND)", party: "INDEPENDENT" },
  { id: "s54", name: "RAMOS, DANILO (MKBYN)", party: "MAKABAYANG KOALISYON NG MAMAMAYAN" },
  { id: "s55", name: "REVILLAME, WILLIE WIL (IND)", party: "INDEPENDENT" },
  { id: "s56", name: "RODRIGUEZ, ATTY. VIC (IND)", party: "INDEPENDENT" },
  { id: "s57", name: "SAHIDULLA, NUR-ANA (IND)", party: "INDEPENDENT" },
  { id: "s58", name: "SALVADOR, PHILLIP IPE (PDPLBN)", party: "PARTIDO DEMOKRATIKO PILIPINO LAKAS NG BAYAN" },
  { id: "s59", name: "SOTTO, TITO (NPC)", party: "NATIONALIST PEOPLE'S COALITION" },
  { id: "s60", name: "TAPADO, MICHAEL BONGBONG (PM)", party: "PARTIDO MANGGAGAWA" },
  { id: "s61", name: "TOLENTINO, FRANCIS TOL (PFP)", party: "PARTIDO FEDERAL NG PILIPINAS" },
  { id: "s62", name: "TULFO, BEN BITAG (IND)", party: "INDEPENDENT" },
  { id: "s63", name: "TULFO, ERWIN (LAKAS)", party: "LAKAS-CHRISTIAN MUSLIM DEMOCRATS" },
  { id: "s64", name: "VALBUENA, MAR MANIBELA (IND)", party: "INDEPENDENT" },
  { id: "s65", name: "VERCELES, LEANDRO (IND)", party: "INDEPENDENT" },
  { id: "s66", name: "VILLAR, CAMILLE (NP)", party: "NACIONALISTA PARTY" }
];
